### ISSUE TITLE
Update Docs

### ISSUE THREAD

**Issue by Ryonez** [PantryParty/docs#10]
The guide currently online here: https://pantryparty.app/ are really out of date. Like, my app has something called `Purchase factor` In create a product. What even is that?

**Comment by arjes** [comment]
When you are on the purchase tab, tap the yellow bar at the top and you will seethe screens listed here: https://pantryparty.app/docs/basic_usage/product-creation.html

The term Purchase Factor is only visible on the Product Creation form and is equivalent to this step: https://pantryparty.app/docs/basic_usage/product-creation.html#step-5-quantity-conversion

Essentially for when you scan one item but add X to stock (think a pack of soda)
