### ISSUE TITLE
iOS won't recognize 8 digit barcodes

### ISSUE THREAD

**Issue by skipper22hassio** [PantryParty/docs#21]
Hello, 

thank you very much for the work on the app. 

I found that many store brands use 8 digit barcodes. The purchase/scan function doesn't recognize them. Example see photo. 

![image](https://user-images.githubusercontent.com/52670824/148822098-b83795b4-bb11-42ae-910f-30a460543c67.jpeg)

13 digit barcodes work. 

The Android app recognizes the barcode. 

iPhone 11 with iOS 15.2

Cheers Sven

**Comment by skipper22hassio** [comment]
Not a "docs" issue, don't know how to move to pantryParty

**Comment by bmalinconico** [comment]
Thanks. I was looking for this issue. I have a new PR that should close it. I'll test it against your example barcode. Thank you
